apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-auth-dex
  namespace: kube-system
spec:
  secretName: cert-auth-dex
  dnsNames:
    - ${DEX_URL}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ${DEX_URL}
  issuerRef:
    name: ${LE_ISSUER}
    kind: ClusterIssuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-auth-login
  namespace: kube-system
spec:
  secretName: cert-auth-login
  dnsNames:
    - ${DEX_LOGIN_URL}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ${DEX_LOGIN_URL}
  issuerRef:
    name: ${LE_ISSUER}
    kind: ClusterIssuer
